# https://www.appveyor.com/docs/lang/nodejs-iojs/
# Test against the latest version of this Node.js version
environment:
  nodejs_version: "10"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  # Output useful info for debugging.
  - node --version
  - npm --version
  - node -e "console.log(process.platform)"
  - node -e "console.log(process.arch)"
  # print cached dependencies
  - echo '%AppData%\npm-cache'
  - echo '%USERPROFILE%\AppData\Local\Cypress\Cache'
  - ls '%AppData%\npm-cache'
  - ls '%USERPROFILE%\AppData\Local\Cypress\Cache'
  - npm ci

cache:
  # cache NPM packages and Cypress binary
  # https://www.appveyor.com/docs/build-cache/
  # https://docs.npmjs.com/files/folders.html#cache
  # https://on.cypress.io/caching
  - '%AppData%\npm-cache' -> package.json
  - '%USERPROFILE%\AppData\Local\Cypress\Cache' -> package.json

test_script:
  - npm run test:ci:windows

# Don't actually build.
build: off
